package com.alienmegacorp.amazonproducts.internals;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated source version: 2.1
 */
@WebServiceClient(name = "AWSECommerceService", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2010-04-01", wsdlLocation = "http://ecs.amazonaws.com/AWSECommerceService/AWSECommerceService.wsdl")
public class AWSECommerceService extends Service
{
    final private static URL AWSECOMMERCESERVICE_WSDL_LOCATION;

    final private static Logger logger = Logger
        .getLogger(com.alienmegacorp.amazonproducts.internals.AWSECommerceService.class.getName());

    static
    {
        URL url = null;
        try
        {
            URL baseUrl;
            baseUrl = com.alienmegacorp.amazonproducts.internals.AWSECommerceService.class.getResource(".");
            url = new URL(baseUrl,
                "http://ecs.amazonaws.com/AWSECommerceService/AWSECommerceService.wsdl");
        }
        catch (final MalformedURLException e)
        {
            logger
                .warning("Failed to create URL for the wsdl Location: 'http://ecs.amazonaws.com/AWSECommerceService/AWSECommerceService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AWSECOMMERCESERVICE_WSDL_LOCATION = url;
    }

    public AWSECommerceService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public AWSECommerceService()
    {
        super(AWSECOMMERCESERVICE_WSDL_LOCATION, new QName(
            "http://webservices.amazon.com/AWSECommerceService/2010-04-01", "AWSECommerceService"));
    }

    /**
     * @return returns AWSECommerceServicePortType
     */
    @WebEndpoint(name = "AWSECommerceServicePort")
    public AWSECommerceServicePortType getAWSECommerceServicePort()
    {
        return super.getPort(new QName(
            "http://webservices.amazon.com/AWSECommerceService/2010-04-01",
            "AWSECommerceServicePort"), AWSECommerceServicePortType.class);
    }

    /**
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *            Supported features not in the <code>features</code> parameter will have their
     *            default values.
     * @return returns AWSECommerceServicePortType
     */
    @WebEndpoint(name = "AWSECommerceServicePort")
    public AWSECommerceServicePortType getAWSECommerceServicePort(WebServiceFeature... features)
    {
        return super.getPort(new QName(
            "http://webservices.amazon.com/AWSECommerceService/2010-04-01",
            "AWSECommerceServicePort"), AWSECommerceServicePortType.class, features);
    }

}
